#!/bin/bash

################################################################################
#Script Name    :script-daemon
#Description    :Pause and continue scripts to bypass rate limiting by an
#                arbitrary amount of time.
#Path           :/usr/bin/
################################################################################

#Send script to background
bash /usr/local/bin/script & 2>&1

PID=$!
echo "Process $PID started.."
while ps -p $PID &> /dev/null; do
    echo "Running $PID..." && sleep 1h
    kill -TSTP $PID
    echo "Sleeping $PID..." && sleep 24h
    kill -SIGCONT $PID
done
